apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: towerfall
data:
  config.yaml: |
    tunnel: ${CF_TUNNEL_ID}
    credentials-file: /etc/cloudflared/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: ${API_DOMAIN}
        service: http://backend-service:4000
        originRequest:
          noTLSVerify: true
      - hostname: ${FRONTEND_DOMAIN}
        service: http://frontend-service:4001
        originRequest:
          noTLSVerify: true
      # Catch-all rule (required)
      - service: http_status:404
