apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: towerfall
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "${CF_ACCOUNT_TAG}",
      "TunnelSecret": "${CF_TUNNEL_SECRET}",
      "TunnelID": "${CF_TUNNEL_ID}"
    }
