name: Lint

on:
  workflow_call:

jobs:
  bot2-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - uses: arduino/setup-task@v2

      - name: Run bot2 linting
        run: task bot2:lint

      - name: Check bot2 formatting
        run: task bot2:format:check

      - name: Run bot2 type checking
        run: task bot2:typecheck

  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - uses: golangci/golangci-lint-action@v6
        with:
          working-directory: backend

      - uses: arduino/setup-task@v2

      - name: Check backend formatting
        run: task be:format:check

      - name: Run go vet
        run: task be:vet

      - name: Run build
        run: task be:build
